In [2]:
import pandas as pd
import numpy as np

In [3]:
# Load raw AI telemetry JSON data from the upstream directory

df = pd.read_json('../data/raw/api_logs_v1_2026-05-19.json')
df.head()

,timestamp,session_id,raw_system_prompt,ai_confidence_score,backend_server_trace,execution_latency_ms
0,2026-05-19 09:02:00,USR_1001,Req_SRC: iOS_15 | STATUS: [HTTP_500_INTERNAL_E...,0.51,Routing -> https://gpu-cluster-delhi.internal....,103.0
1,2026-05-19 09:04:00,USR_1002,Req_SRC: Web_Dashboard | STATUS: [HTTP_429_RAT...,0.52,Routing -> https://eu-west-1.aws.internal:443/...,105.5
2,2026-05-19 09:06:00,USR_1003,Req_SRC: API_Client | STATUS: [HTTP_403_FORBID...,0.53,Routing -> https://ai-node-04.delhi.server.int...,108.0
3,2026-05-19 09:08:00,USR_1004,Req_SRC: Android_App | STATUS: [HTTP_200_OK] |...,0.54,Routing -> https://gpu-cluster-delhi.internal....,110.5
4,2026-05-19 09:10:00,USR_1005,Req_SRC: iOS_15 | STATUS: [HTTP_500_INTERNAL_E...,0.55,Routing -> https://eu-west-1.aws.internal:443/...,113.0

In [4]:
df.shape

(200, 6)

In [5]:
df.columns

Index(['timestamp', 'session_id', 'raw_system_prompt', 'ai_confidence_score',
       'backend_server_trace', 'execution_latency_ms'],
      dtype='str')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   timestamp             200 non-null    datetime64[us]
 1   session_id            200 non-null    str
 2   raw_system_prompt     200 non-null    str
 3   ai_confidence_score   180 non-null    object
 4   backend_server_trace  190 non-null    str
 5   execution_latency_ms  193 non-null    object
dtypes: datetime64[us](1), object(2), str(3)
memory usage: 9.5+ KB

In [7]:
df.describe()

                 timestamp
count                  200
mean   2026-05-19 12:21:00
min    2026-05-19 09:02:00
25%    2026-05-19 10:41:30
50%    2026-05-19 12:21:00
75%    2026-05-19 14:00:30
max    2026-05-19 15:40:00

In [8]:
df.isna().sum()

timestamp                0
session_id               0
raw_system_prompt        0
ai_confidence_score     20
backend_server_trace    10
execution_latency_ms     7
dtype: int64

In [9]:
df.head()

,timestamp,session_id,raw_system_prompt,ai_confidence_score,backend_server_trace,execution_latency_ms
0,2026-05-19 09:02:00,USR_1001,Req_SRC: iOS_15 | STATUS: [HTTP_500_INTERNAL_E...,0.51,Routing -> https://gpu-cluster-delhi.internal....,103.0
1,2026-05-19 09:04:00,USR_1002,Req_SRC: Web_Dashboard | STATUS: [HTTP_429_RAT...,0.52,Routing -> https://eu-west-1.aws.internal:443/...,105.5
2,2026-05-19 09:06:00,USR_1003,Req_SRC: API_Client | STATUS: [HTTP_403_FORBID...,0.53,Routing -> https://ai-node-04.delhi.server.int...,108.0
3,2026-05-19 09:08:00,USR_1004,Req_SRC: Android_App | STATUS: [HTTP_200_OK] |...,0.54,Routing -> https://gpu-cluster-delhi.internal....,110.5
4,2026-05-19 09:10:00,USR_1005,Req_SRC: iOS_15 | STATUS: [HTTP_500_INTERNAL_E...,0.55,Routing -> https://eu-west-1.aws.internal:443/...,113.0

In [10]:
# Standardize messy timestamps into a uniform Pandas datetime format

df['timestamp'] = pd.to_datetime(df['timestamp'])

In [11]:
# Fill missing server traces with a default categorical placeholder

df.fillna({'backend_server_trace': "Unknown_Route"}, inplace=True)

,timestamp,session_id,raw_system_prompt,ai_confidence_score,backend_server_trace,execution_latency_ms
0,2026-05-19 09:02:00,USR_1001,Req_SRC: iOS_15 | STATUS: [HTTP_500_INTERNAL_E...,0.51,Routing -> https://gpu-cluster-delhi.internal....,103.0
1,2026-05-19 09:04:00,USR_1002,Req_SRC: Web_Dashboard | STATUS: [HTTP_429_RAT...,0.52,Routing -> https://eu-west-1.aws.internal:443/...,105.5
2,2026-05-19 09:06:00,USR_1003,Req_SRC: API_Client | STATUS: [HTTP_403_FORBID...,0.53,Routing -> https://ai-node-04.delhi.server.int...,108.0
3,2026-05-19 09:08:00,USR_1004,Req_SRC: Android_App | STATUS: [HTTP_200_OK] |...,0.54,Routing -> https://gpu-cluster-delhi.internal....,110.5
4,2026-05-19 09:10:00,USR_1005,Req_SRC: iOS_15 | STATUS: [HTTP_500_INTERNAL_E...,0.55,Routing -> https://eu-west-1.aws.internal:443/...,113.0
...,...,...,...,...,...,...
195,2026-05-19 15:32:00,USR_1196,Req_SRC: Android_App | STATUS: [HTTP_200_OK] |...,86%,Routing -> https://gpu-cluster-delhi.internal....,590.5
196,2026-05-19 15:34:00,USR_1197,Req_SRC: iOS_15 | STATUS: [HTTP_500_INTERNAL_E...,0.51,Routing -> https://eu-west-1.aws.internal:443/...,593.0
197,2026-05-19 15:36:00,USR_1198,Req_SRC: Web_Dashboard | STATUS: [HTTP_429_RAT...,0.52,Routing -> https://ai-node-04.delhi.server.int...,595.5
198,2026-05-19 15:38:00,USR_1199,Req_SRC: API_Client | STATUS: [HTTP_403_FORBID...,0.53,Routing -> https://gpu-cluster-delhi.internal....,598.0
199,2026-05-19 15:40:00,USR_1200,Req_SRC: Android_App | STATUS: [HTTP_200_OK] |...,None,Unknown_Route,timeout_error

In [12]:
df.head()

,timestamp,session_id,raw_system_prompt,ai_confidence_score,backend_server_trace,execution_latency_ms
0,2026-05-19 09:02:00,USR_1001,Req_SRC: iOS_15 | STATUS: [HTTP_500_INTERNAL_E...,0.51,Routing -> https://gpu-cluster-delhi.internal....,103.0
1,2026-05-19 09:04:00,USR_1002,Req_SRC: Web_Dashboard | STATUS: [HTTP_429_RAT...,0.52,Routing -> https://eu-west-1.aws.internal:443/...,105.5
2,2026-05-19 09:06:00,USR_1003,Req_SRC: API_Client | STATUS: [HTTP_403_FORBID...,0.53,Routing -> https://ai-node-04.delhi.server.int...,108.0
3,2026-05-19 09:08:00,USR_1004,Req_SRC: Android_App | STATUS: [HTTP_200_OK] |...,0.54,Routing -> https://gpu-cluster-delhi.internal....,110.5
4,2026-05-19 09:10:00,USR_1005,Req_SRC: iOS_15 | STATUS: [HTTP_500_INTERNAL_E...,0.55,Routing -> https://eu-west-1.aws.internal:443/...,113.0

In [13]:
df.loc[df['execution_latency_ms'] == "timeout_error", 'execution_latency_ms'] = 5000.0

In [14]:
# Force-convert column to float to enable statistical operations

df['execution_latency_ms'] = pd.to_numeric(df['execution_latency_ms'], errors='coerce')

In [15]:
# Impute missing latencies using median to prevent skewness from high outliers

df.fillna({'execution_latency_ms': df['execution_latency_ms'].median()}, inplace=True)

,timestamp,session_id,raw_system_prompt,ai_confidence_score,backend_server_trace,execution_latency_ms
0,2026-05-19 09:02:00,USR_1001,Req_SRC: iOS_15 | STATUS: [HTTP_500_INTERNAL_E...,0.51,Routing -> https://gpu-cluster-delhi.internal....,103.0
1,2026-05-19 09:04:00,USR_1002,Req_SRC: Web_Dashboard | STATUS: [HTTP_429_RAT...,0.52,Routing -> https://eu-west-1.aws.internal:443/...,105.5
2,2026-05-19 09:06:00,USR_1003,Req_SRC: API_Client | STATUS: [HTTP_403_FORBID...,0.53,Routing -> https://ai-node-04.delhi.server.int...,108.0
3,2026-05-19 09:08:00,USR_1004,Req_SRC: Android_App | STATUS: [HTTP_200_OK] |...,0.54,Routing -> https://gpu-cluster-delhi.internal....,110.5
4,2026-05-19 09:10:00,USR_1005,Req_SRC: iOS_15 | STATUS: [HTTP_500_INTERNAL_E...,0.55,Routing -> https://eu-west-1.aws.internal:443/...,113.0
...,...,...,...,...,...,...
195,2026-05-19 15:32:00,USR_1196,Req_SRC: Android_App | STATUS: [HTTP_200_OK] |...,86%,Routing -> https://gpu-cluster-delhi.internal....,590.5
196,2026-05-19 15:34:00,USR_1197,Req_SRC: iOS_15 | STATUS: [HTTP_500_INTERNAL_E...,0.51,Routing -> https://eu-west-1.aws.internal:443/...,593.0
197,2026-05-19 15:36:00,USR_1198,Req_SRC: Web_Dashboard | STATUS: [HTTP_429_RAT...,0.52,Routing -> https://ai-node-04.delhi.server.int...,595.5
198,2026-05-19 15:38:00,USR_1199,Req_SRC: API_Client | STATUS: [HTTP_403_FORBID...,0.53,Routing -> https://gpu-cluster-delhi.internal....,598.0
199,2026-05-19 15:40:00,USR_1200,Req_SRC: Android_App | STATUS: [HTTP_200_OK] |...,None,Unknown_Route,5000.0

In [16]:
# Standardize 'High' tags to 0.99

df['ai_confidence_score'] = df['ai_confidence_score'].replace("High", 0.99)

In [17]:
df['ai_confidence_score'] = df['ai_confidence_score'].apply(
    lambda x: float(x.replace('%', '')) / 100 if isinstance(x, str) and '%' in x else x
)

In [18]:
# Force-convert column to float to enable statistical operations

df['ai_confidence_score'] = pd.to_numeric(df['ai_confidence_score'], errors='coerce')

In [19]:
# Impute missing confidence scores using the column mean

df.loc[df['ai_confidence_score'].isna(), 'ai_confidence_score'] = df['ai_confidence_score'].mean()

In [20]:
# Verify zero null values and proper enforcement of schema data types

df.isna().sum()

timestamp               0
session_id              0
raw_system_prompt       0
ai_confidence_score     0
backend_server_trace    0
execution_latency_ms    0
dtype: int64

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   timestamp             200 non-null    datetime64[us]
 1   session_id            200 non-null    str
 2   raw_system_prompt     200 non-null    str
 3   ai_confidence_score   200 non-null    float64
 4   backend_server_trace  200 non-null    str
 5   execution_latency_ms  200 non-null    float64
dtypes: datetime64[us](1), float64(2), str(3)
memory usage: 9.5 KB

In [24]:
df.to_csv('../data/processed/api_logs_v1_cleaned_2026-05-19.csv', index= False)