In [125]:
import pandas as pd
import numpy as np

In [ ]:
# Load the cleaned dataset

df = pd.read_csv('../data/processed/api_logs_v1_cleaned_2026-05-19.csv')
df.head()

,timestamp,session_id,raw_system_prompt,ai_confidence_score,backend_server_trace,execution_latency_ms
0,2026-05-19 09:02:00,USR_1001,Req_SRC: iOS_15 | STATUS: [HTTP_500_INTERNAL_E...,0.51,Routing -> https://gpu-cluster-delhi.internal....,103.0
1,2026-05-19 09:04:00,USR_1002,Req_SRC: Web_Dashboard | STATUS: [HTTP_429_RAT...,0.52,Routing -> https://eu-west-1.aws.internal:443/...,105.5
2,2026-05-19 09:06:00,USR_1003,Req_SRC: API_Client | STATUS: [HTTP_403_FORBID...,0.53,Routing -> https://ai-node-04.delhi.server.int...,108.0
3,2026-05-19 09:08:00,USR_1004,Req_SRC: Android_App | STATUS: [HTTP_200_OK] |...,0.54,Routing -> https://gpu-cluster-delhi.internal....,110.5
4,2026-05-19 09:10:00,USR_1005,Req_SRC: iOS_15 | STATUS: [HTTP_500_INTERNAL_E...,0.55,Routing -> https://eu-west-1.aws.internal:443/...,113.0

In [127]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   timestamp             200 non-null    str
 1   session_id            200 non-null    str
 2   raw_system_prompt     200 non-null    str
 3   ai_confidence_score   200 non-null    float64
 4   backend_server_trace  200 non-null    str
 5   execution_latency_ms  200 non-null    float64
dtypes: float64(2), str(4)
memory usage: 9.5 KB

In [128]:
df.columns

Index(['timestamp', 'session_id', 'raw_system_prompt', 'ai_confidence_score',
       'backend_server_trace', 'execution_latency_ms'],
      dtype='str')

In [129]:
df.iloc[0]['raw_system_prompt']

'Req_SRC: iOS_15 | STATUS: [HTTP_500_INTERNAL_ERROR] | Msg: Write a python code'

In [ ]:
# Extract 'device_type', 'http_status', and 'user_query' from the raw prompt string

df[['device_type', 'http_status', 'user_query']] = df['raw_system_prompt'].str.split('|', expand=True)

In [131]:
df.head()

,timestamp,session_id,raw_system_prompt,ai_confidence_score,backend_server_trace,execution_latency_ms,device_type,http_status,user_query
0,2026-05-19 09:02:00,USR_1001,Req_SRC: iOS_15 | STATUS: [HTTP_500_INTERNAL_E...,0.51,Routing -> https://gpu-cluster-delhi.internal....,103.0,Req_SRC: iOS_15,STATUS: [HTTP_500_INTERNAL_ERROR],Msg: Write a python code
1,2026-05-19 09:04:00,USR_1002,Req_SRC: Web_Dashboard | STATUS: [HTTP_429_RAT...,0.52,Routing -> https://eu-west-1.aws.internal:443/...,105.5,Req_SRC: Web_Dashboard,STATUS: [HTTP_429_RATE_LIMIT],Msg: Explain quantum physics
2,2026-05-19 09:06:00,USR_1003,Req_SRC: API_Client | STATUS: [HTTP_403_FORBID...,0.53,Routing -> https://ai-node-04.delhi.server.int...,108.0,Req_SRC: API_Client,STATUS: [HTTP_403_FORBIDDEN],Msg: Write a python code
3,2026-05-19 09:08:00,USR_1004,Req_SRC: Android_App | STATUS: [HTTP_200_OK] |...,0.54,Routing -> https://gpu-cluster-delhi.internal....,110.5,Req_SRC: Android_App,STATUS: [HTTP_200_OK],Msg: Explain quantum physics
4,2026-05-19 09:10:00,USR_1005,Req_SRC: iOS_15 | STATUS: [HTTP_500_INTERNAL_E...,0.55,Routing -> https://eu-west-1.aws.internal:443/...,113.0,Req_SRC: iOS_15,STATUS: [HTTP_500_INTERNAL_ERROR],Msg: Write a python code

In [ ]:
# Remove the original 'raw_system_prompt' column as it is no longer needed

df.drop(columns=['raw_system_prompt'], inplace=True)

In [133]:
df.head()

,timestamp,session_id,ai_confidence_score,backend_server_trace,execution_latency_ms,device_type,http_status,user_query
0,2026-05-19 09:02:00,USR_1001,0.51,Routing -> https://gpu-cluster-delhi.internal....,103.0,Req_SRC: iOS_15,STATUS: [HTTP_500_INTERNAL_ERROR],Msg: Write a python code
1,2026-05-19 09:04:00,USR_1002,0.52,Routing -> https://eu-west-1.aws.internal:443/...,105.5,Req_SRC: Web_Dashboard,STATUS: [HTTP_429_RATE_LIMIT],Msg: Explain quantum physics
2,2026-05-19 09:06:00,USR_1003,0.53,Routing -> https://ai-node-04.delhi.server.int...,108.0,Req_SRC: API_Client,STATUS: [HTTP_403_FORBIDDEN],Msg: Write a python code
3,2026-05-19 09:08:00,USR_1004,0.54,Routing -> https://gpu-cluster-delhi.internal....,110.5,Req_SRC: Android_App,STATUS: [HTTP_200_OK],Msg: Explain quantum physics
4,2026-05-19 09:10:00,USR_1005,0.55,Routing -> https://eu-west-1.aws.internal:443/...,113.0,Req_SRC: iOS_15,STATUS: [HTTP_500_INTERNAL_ERROR],Msg: Write a python code

In [ ]:
# Clean 'device_type': remove prefix and extra spaces

df['device_type'] = df['device_type'].str.replace('Req_SRC:', '').str.strip()

In [ ]:
# Clean 'http_status': remove prefix, brackets, and extra spaces

df['http_status'] = df['http_status'].str.replace('STATUS:', '').str.replace('[', '').str.replace(']', '').str.strip()

In [ ]:
# Clean 'user_query': remove prefix and extra spaces

df['user_query'] = df['user_query'].str.replace('Msg: ', '').str.strip()

In [137]:
df.head()

,timestamp,session_id,ai_confidence_score,backend_server_trace,execution_latency_ms,device_type,http_status,user_query
0,2026-05-19 09:02:00,USR_1001,0.51,Routing -> https://gpu-cluster-delhi.internal....,103.0,iOS_15,HTTP_500_INTERNAL_ERROR,Write a python code
1,2026-05-19 09:04:00,USR_1002,0.52,Routing -> https://eu-west-1.aws.internal:443/...,105.5,Web_Dashboard,HTTP_429_RATE_LIMIT,Explain quantum physics
2,2026-05-19 09:06:00,USR_1003,0.53,Routing -> https://ai-node-04.delhi.server.int...,108.0,API_Client,HTTP_403_FORBIDDEN,Write a python code
3,2026-05-19 09:08:00,USR_1004,0.54,Routing -> https://gpu-cluster-delhi.internal....,110.5,Android_App,HTTP_200_OK,Explain quantum physics
4,2026-05-19 09:10:00,USR_1005,0.55,Routing -> https://eu-west-1.aws.internal:443/...,113.0,iOS_15,HTTP_500_INTERNAL_ERROR,Write a python code

In [ ]:
# Convert 'timestamp' column to datetime format, handling errors

df['timestamp'] = pd.to_datetime(df['timestamp'], errors='coerce')

In [ ]:
# Extract the 'hour' from the timestamp to analyze time-based patterns

df['hour_of_day'] = df['timestamp'].dt.hour

In [ ]:
# Drop the original 'timestamp' column to keep the dataframe concise

df.drop(columns=['timestamp'], inplace=True)

In [141]:
df.head()

,session_id,ai_confidence_score,backend_server_trace,execution_latency_ms,device_type,http_status,user_query,hour_of_day
0,USR_1001,0.51,Routing -> https://gpu-cluster-delhi.internal....,103.0,iOS_15,HTTP_500_INTERNAL_ERROR,Write a python code,9
1,USR_1002,0.52,Routing -> https://eu-west-1.aws.internal:443/...,105.5,Web_Dashboard,HTTP_429_RATE_LIMIT,Explain quantum physics,9
2,USR_1003,0.53,Routing -> https://ai-node-04.delhi.server.int...,108.0,API_Client,HTTP_403_FORBIDDEN,Write a python code,9
3,USR_1004,0.54,Routing -> https://gpu-cluster-delhi.internal....,110.5,Android_App,HTTP_200_OK,Explain quantum physics,9
4,USR_1005,0.55,Routing -> https://eu-west-1.aws.internal:443/...,113.0,iOS_15,HTTP_500_INTERNAL_ERROR,Write a python code,9

In [142]:
df.iloc[0]['backend_server_trace']

'Routing -> https://gpu-cluster-delhi.internal.net:9092/v1/chat'

In [143]:
df.iloc[1]['backend_server_trace']

'Routing -> https://eu-west-1.aws.internal:443/v1/chat'

In [ ]:
# Clean 'backend_server_trace': remove prefix URL

df['backend_server_trace'] = df['backend_server_trace'].str.replace('Routing -> https://', "").str.strip()

In [145]:
df.iloc[1]['backend_server_trace']

'eu-west-1.aws.internal:443/v1/chat'

In [ ]:
# Keep only the core server identifier by splitting at the first period

df['backend_server_trace'] = df['backend_server_trace'].apply(lambda x: x.split('.')[0])

In [147]:
df.head()

,session_id,ai_confidence_score,backend_server_trace,execution_latency_ms,device_type,http_status,user_query,hour_of_day
0,USR_1001,0.51,gpu-cluster-delhi,103.0,iOS_15,HTTP_500_INTERNAL_ERROR,Write a python code,9
1,USR_1002,0.52,eu-west-1,105.5,Web_Dashboard,HTTP_429_RATE_LIMIT,Explain quantum physics,9
2,USR_1003,0.53,ai-node-04,108.0,API_Client,HTTP_403_FORBIDDEN,Write a python code,9
3,USR_1004,0.54,gpu-cluster-delhi,110.5,Android_App,HTTP_200_OK,Explain quantum physics,9
4,USR_1005,0.55,eu-west-1,113.0,iOS_15,HTTP_500_INTERNAL_ERROR,Write a python code,9

In [ ]:
# Create a binary target variable 'is_error': 0 for successful requests, 1 for errors

df['is_error'] = np.where(df['http_status'] == 'HTTP_200_OK', 0, 1)

In [149]:
df.head()

,session_id,ai_confidence_score,backend_server_trace,execution_latency_ms,device_type,http_status,user_query,hour_of_day,is_error
0,USR_1001,0.51,gpu-cluster-delhi,103.0,iOS_15,HTTP_500_INTERNAL_ERROR,Write a python code,9,1
1,USR_1002,0.52,eu-west-1,105.5,Web_Dashboard,HTTP_429_RATE_LIMIT,Explain quantum physics,9,1
2,USR_1003,0.53,ai-node-04,108.0,API_Client,HTTP_403_FORBIDDEN,Write a python code,9,1
3,USR_1004,0.54,gpu-cluster-delhi,110.5,Android_App,HTTP_200_OK,Explain quantum physics,9,0
4,USR_1005,0.55,eu-west-1,113.0,iOS_15,HTTP_500_INTERNAL_ERROR,Write a python code,9,1

In [ ]:
# Calculate and store the character length of each user query

df['query_length'] = df['user_query'].str.len()

In [151]:
df.head()

,session_id,ai_confidence_score,backend_server_trace,execution_latency_ms,device_type,http_status,user_query,hour_of_day,is_error,query_length
0,USR_1001,0.51,gpu-cluster-delhi,103.0,iOS_15,HTTP_500_INTERNAL_ERROR,Write a python code,9,1,19
1,USR_1002,0.52,eu-west-1,105.5,Web_Dashboard,HTTP_429_RATE_LIMIT,Explain quantum physics,9,1,23
2,USR_1003,0.53,ai-node-04,108.0,API_Client,HTTP_403_FORBIDDEN,Write a python code,9,1,19
3,USR_1004,0.54,gpu-cluster-delhi,110.5,Android_App,HTTP_200_OK,Explain quantum physics,9,0,23
4,USR_1005,0.55,eu-west-1,113.0,iOS_15,HTTP_500_INTERNAL_ERROR,Write a python code,9,1,19

In [ ]:
# Convert 'device_type' into numerical dummy variables for machine learning models

df = pd.get_dummies(df, columns= ['device_type'], prefix='device', dtype= int)

In [154]:
df.head()

,session_id,ai_confidence_score,backend_server_trace,execution_latency_ms,http_status,user_query,hour_of_day,is_error,query_length,device_API_Client,device_Android_App,device_Web_Dashboard,device_iOS_15
0,USR_1001,0.51,gpu-cluster-delhi,103.0,HTTP_500_INTERNAL_ERROR,Write a python code,9,1,19,0,0,0,1
1,USR_1002,0.52,eu-west-1,105.5,HTTP_429_RATE_LIMIT,Explain quantum physics,9,1,23,0,0,1,0
2,USR_1003,0.53,ai-node-04,108.0,HTTP_403_FORBIDDEN,Write a python code,9,1,19,1,0,0,0
3,USR_1004,0.54,gpu-cluster-delhi,110.5,HTTP_200_OK,Explain quantum physics,9,0,23,0,1,0,0
4,USR_1005,0.55,eu-west-1,113.0,HTTP_500_INTERNAL_ERROR,Write a python code,9,1,19,0,0,0,1

In [153]:
df.to_csv('../data/processed/api_logs_v1_features_added_2026-05-19.csv', index=False)